/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthMagicLinkRouteImport } from './routes/auth.magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AppTransferenciasRouteImport } from './routes/app.transferencias'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppObrasRouteImport } from './routes/app.obras'
import { Route as AppFornecedoresRouteImport } from './routes/app.fornecedores'
import { Route as AppFluxoCaixaRouteImport } from './routes/app.fluxo-caixa'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'
import { Route as AppContasReceberRouteImport } from './routes/app.contas-receber'
import { Route as AppContasPagarRouteImport } from './routes/app.contas-pagar'
import { Route as AppContasBancariasRouteImport } from './routes/app.contas-bancarias'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppConciliacaoRouteImport } from './routes/app.conciliacao'
import { Route as AppCategoriasRouteImport } from './routes/app.categorias'
import { Route as AppCartoesRouteImport } from './routes/app.cartoes'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminFaturasRouteImport } from './routes/admin.faturas'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AppRhColaboradoresRouteImport } from './routes/app.rh.colaboradores'
import { Route as AppEstoqueSaldosRouteImport } from './routes/app.estoque.saldos'
import { Route as AppEstoqueRequisicoesRouteImport } from './routes/app.estoque.requisicoes'
import { Route as AppEstoqueProdutosRouteImport } from './routes/app.estoque.produtos'
import { Route as AppEstoqueMovimentacoesRouteImport } from './routes/app.estoque.movimentacoes'
import { Route as AppEstoqueAlmoxarifadosRouteImport } from './routes/app.estoque.almoxarifados'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppObrasObraIdRdoRouteImport } from './routes/app.obras.$obraId.rdo'
import { Route as AppObrasObraIdOrcamentoRouteImport } from './routes/app.obras.$obraId.orcamento'
import { Route as AppObrasObraIdComprasRouteImport } from './routes/app.obras.$obraId.compras'
import { Route as AppObrasObraIdRdoRdoIdRouteImport } from './routes/app.obras.$obraId.rdo.$rdoId'
import { Route as AppObrasObraIdComprasCompraIdRouteImport } from './routes/app.obras.$obraId.compras.$compraId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/auth/magic-link',
  path: '/auth/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferenciasRoute = AppTransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppContasReceberRoute = AppContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => AppRoute,
} as any)
const AppContasPagarRoute = AppContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppContasBancariasRoute = AppContasBancariasRouteImport.update({
  id: '/contas-bancarias',
  path: '/contas-bancarias',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConciliacaoRoute = AppConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturasRoute = AdminFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AppRhColaboradoresRoute = AppRhColaboradoresRouteImport.update({
  id: '/rh/colaboradores',
  path: '/rh/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueSaldosRoute = AppEstoqueSaldosRouteImport.update({
  id: '/estoque/saldos',
  path: '/estoque/saldos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRequisicoesRoute = AppEstoqueRequisicoesRouteImport.update({
  id: '/estoque/requisicoes',
  path: '/estoque/requisicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueProdutosRoute = AppEstoqueProdutosRouteImport.update({
  id: '/estoque/produtos',
  path: '/estoque/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueMovimentacoesRoute = AppEstoqueMovimentacoesRouteImport.update({
  id: '/estoque/movimentacoes',
  path: '/estoque/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueAlmoxarifadosRoute = AppEstoqueAlmoxarifadosRouteImport.update({
  id: '/estoque/almoxarifados',
  path: '/estoque/almoxarifados',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppObrasObraIdRdoRoute = AppObrasObraIdRdoRouteImport.update({
  id: '/$obraId/rdo',
  path: '/$obraId/rdo',
  getParentRoute: () => AppObrasRoute,
} as any)
const AppObrasObraIdOrcamentoRoute = AppObrasObraIdOrcamentoRouteImport.update({
  id: '/$obraId/orcamento',
  path: '/$obraId/orcamento',
  getParentRoute: () => AppObrasRoute,
} as any)
const AppObrasObraIdComprasRoute = AppObrasObraIdComprasRouteImport.update({
  id: '/$obraId/compras',
  path: '/$obraId/compras',
  getParentRoute: () => AppObrasRoute,
} as any)
const AppObrasObraIdRdoRdoIdRoute = AppObrasObraIdRdoRdoIdRouteImport.update({
  id: '/$rdoId',
  path: '/$rdoId',
  getParentRoute: () => AppObrasObraIdRdoRoute,
} as any)
const AppObrasObraIdComprasCompraIdRoute =
  AppObrasObraIdComprasCompraIdRouteImport.update({
    id: '/$compraId',
    path: '/$compraId',
    getParentRoute: () => AppObrasObraIdComprasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturas': typeof AdminFaturasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/conciliacao': typeof AppConciliacaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas-bancarias': typeof AppContasBancariasRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/estoque/almoxarifados': typeof AppEstoqueAlmoxarifadosRoute
  '/app/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/app/estoque/produtos': typeof AppEstoqueProdutosRoute
  '/app/estoque/requisicoes': typeof AppEstoqueRequisicoesRoute
  '/app/estoque/saldos': typeof AppEstoqueSaldosRoute
  '/app/rh/colaboradores': typeof AppRhColaboradoresRoute
  '/app/obras/$obraId/compras': typeof AppObrasObraIdComprasRouteWithChildren
  '/app/obras/$obraId/orcamento': typeof AppObrasObraIdOrcamentoRoute
  '/app/obras/$obraId/rdo': typeof AppObrasObraIdRdoRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/obras/$obraId/compras/$compraId': typeof AppObrasObraIdComprasCompraIdRoute
  '/app/obras/$obraId/rdo/$rdoId': typeof AppObrasObraIdRdoRdoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturas': typeof AdminFaturasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/conciliacao': typeof AppConciliacaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas-bancarias': typeof AppContasBancariasRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/estoque/almoxarifados': typeof AppEstoqueAlmoxarifadosRoute
  '/app/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/app/estoque/produtos': typeof AppEstoqueProdutosRoute
  '/app/estoque/requisicoes': typeof AppEstoqueRequisicoesRoute
  '/app/estoque/saldos': typeof AppEstoqueSaldosRoute
  '/app/rh/colaboradores': typeof AppRhColaboradoresRoute
  '/app/obras/$obraId/compras': typeof AppObrasObraIdComprasRouteWithChildren
  '/app/obras/$obraId/orcamento': typeof AppObrasObraIdOrcamentoRoute
  '/app/obras/$obraId/rdo': typeof AppObrasObraIdRdoRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/obras/$obraId/compras/$compraId': typeof AppObrasObraIdComprasCompraIdRoute
  '/app/obras/$obraId/rdo/$rdoId': typeof AppObrasObraIdRdoRdoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturas': typeof AdminFaturasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/cartoes': typeof AppCartoesRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/conciliacao': typeof AppConciliacaoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas-bancarias': typeof AppContasBancariasRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/transferencias': typeof AppTransferenciasRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/estoque/almoxarifados': typeof AppEstoqueAlmoxarifadosRoute
  '/app/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/app/estoque/produtos': typeof AppEstoqueProdutosRoute
  '/app/estoque/requisicoes': typeof AppEstoqueRequisicoesRoute
  '/app/estoque/saldos': typeof AppEstoqueSaldosRoute
  '/app/rh/colaboradores': typeof AppRhColaboradoresRoute
  '/app/obras/$obraId/compras': typeof AppObrasObraIdComprasRouteWithChildren
  '/app/obras/$obraId/orcamento': typeof AppObrasObraIdOrcamentoRoute
  '/app/obras/$obraId/rdo': typeof AppObrasObraIdRdoRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/obras/$obraId/compras/$compraId': typeof AppObrasObraIdComprasCompraIdRoute
  '/app/obras/$obraId/rdo/$rdoId': typeof AppObrasObraIdRdoRdoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturas'
    | '/admin/planos'
    | '/admin/tickets'
    | '/app/cartoes'
    | '/app/categorias'
    | '/app/conciliacao'
    | '/app/configuracoes'
    | '/app/contas-bancarias'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/empresas'
    | '/app/fluxo-caixa'
    | '/app/fornecedores'
    | '/app/obras'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/transferencias'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/admin/'
    | '/app/'
    | '/app/estoque/almoxarifados'
    | '/app/estoque/movimentacoes'
    | '/app/estoque/produtos'
    | '/app/estoque/requisicoes'
    | '/app/estoque/saldos'
    | '/app/rh/colaboradores'
    | '/app/obras/$obraId/compras'
    | '/app/obras/$obraId/orcamento'
    | '/app/obras/$obraId/rdo'
    | '/lovable/email/queue/process'
    | '/app/obras/$obraId/compras/$compraId'
    | '/app/obras/$obraId/rdo/$rdoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturas'
    | '/admin/planos'
    | '/admin/tickets'
    | '/app/cartoes'
    | '/app/categorias'
    | '/app/conciliacao'
    | '/app/configuracoes'
    | '/app/contas-bancarias'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/empresas'
    | '/app/fluxo-caixa'
    | '/app/fornecedores'
    | '/app/obras'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/transferencias'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/admin'
    | '/app'
    | '/app/estoque/almoxarifados'
    | '/app/estoque/movimentacoes'
    | '/app/estoque/produtos'
    | '/app/estoque/requisicoes'
    | '/app/estoque/saldos'
    | '/app/rh/colaboradores'
    | '/app/obras/$obraId/compras'
    | '/app/obras/$obraId/orcamento'
    | '/app/obras/$obraId/rdo'
    | '/lovable/email/queue/process'
    | '/app/obras/$obraId/compras/$compraId'
    | '/app/obras/$obraId/rdo/$rdoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturas'
    | '/admin/planos'
    | '/admin/tickets'
    | '/app/cartoes'
    | '/app/categorias'
    | '/app/conciliacao'
    | '/app/configuracoes'
    | '/app/contas-bancarias'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/empresas'
    | '/app/fluxo-caixa'
    | '/app/fornecedores'
    | '/app/obras'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/transferencias'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/admin/'
    | '/app/'
    | '/app/estoque/almoxarifados'
    | '/app/estoque/movimentacoes'
    | '/app/estoque/produtos'
    | '/app/estoque/requisicoes'
    | '/app/estoque/saldos'
    | '/app/rh/colaboradores'
    | '/app/obras/$obraId/compras'
    | '/app/obras/$obraId/orcamento'
    | '/app/obras/$obraId/rdo'
    | '/lovable/email/queue/process'
    | '/app/obras/$obraId/compras/$compraId'
    | '/app/obras/$obraId/rdo/$rdoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/auth/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transferencias': {
      id: '/app/transferencias'
      path: '/transferencias'
      fullPath: '/app/transferencias'
      preLoaderRoute: typeof AppTransferenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/obras': {
      id: '/app/obras'
      path: '/obras'
      fullPath: '/app/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores': {
      id: '/app/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fluxo-caixa': {
      id: '/app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/app/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-receber': {
      id: '/app/contas-receber'
      path: '/contas-receber'
      fullPath: '/app/contas-receber'
      preLoaderRoute: typeof AppContasReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-pagar': {
      id: '/app/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/app/contas-pagar'
      preLoaderRoute: typeof AppContasPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-bancarias': {
      id: '/app/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/app/contas-bancarias'
      preLoaderRoute: typeof AppContasBancariasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conciliacao': {
      id: '/app/conciliacao'
      path: '/conciliacao'
      fullPath: '/app/conciliacao'
      preLoaderRoute: typeof AppConciliacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cartoes': {
      id: '/app/cartoes'
      path: '/cartoes'
      fullPath: '/app/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturas': {
      id: '/admin/faturas'
      path: '/faturas'
      fullPath: '/admin/faturas'
      preLoaderRoute: typeof AdminFaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/rh/colaboradores': {
      id: '/app/rh/colaboradores'
      path: '/rh/colaboradores'
      fullPath: '/app/rh/colaboradores'
      preLoaderRoute: typeof AppRhColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/saldos': {
      id: '/app/estoque/saldos'
      path: '/estoque/saldos'
      fullPath: '/app/estoque/saldos'
      preLoaderRoute: typeof AppEstoqueSaldosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/requisicoes': {
      id: '/app/estoque/requisicoes'
      path: '/estoque/requisicoes'
      fullPath: '/app/estoque/requisicoes'
      preLoaderRoute: typeof AppEstoqueRequisicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/produtos': {
      id: '/app/estoque/produtos'
      path: '/estoque/produtos'
      fullPath: '/app/estoque/produtos'
      preLoaderRoute: typeof AppEstoqueProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/movimentacoes': {
      id: '/app/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/app/estoque/movimentacoes'
      preLoaderRoute: typeof AppEstoqueMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/almoxarifados': {
      id: '/app/estoque/almoxarifados'
      path: '/estoque/almoxarifados'
      fullPath: '/app/estoque/almoxarifados'
      preLoaderRoute: typeof AppEstoqueAlmoxarifadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/obras/$obraId/rdo': {
      id: '/app/obras/$obraId/rdo'
      path: '/$obraId/rdo'
      fullPath: '/app/obras/$obraId/rdo'
      preLoaderRoute: typeof AppObrasObraIdRdoRouteImport
      parentRoute: typeof AppObrasRoute
    }
    '/app/obras/$obraId/orcamento': {
      id: '/app/obras/$obraId/orcamento'
      path: '/$obraId/orcamento'
      fullPath: '/app/obras/$obraId/orcamento'
      preLoaderRoute: typeof AppObrasObraIdOrcamentoRouteImport
      parentRoute: typeof AppObrasRoute
    }
    '/app/obras/$obraId/compras': {
      id: '/app/obras/$obraId/compras'
      path: '/$obraId/compras'
      fullPath: '/app/obras/$obraId/compras'
      preLoaderRoute: typeof AppObrasObraIdComprasRouteImport
      parentRoute: typeof AppObrasRoute
    }
    '/app/obras/$obraId/rdo/$rdoId': {
      id: '/app/obras/$obraId/rdo/$rdoId'
      path: '/$rdoId'
      fullPath: '/app/obras/$obraId/rdo/$rdoId'
      preLoaderRoute: typeof AppObrasObraIdRdoRdoIdRouteImport
      parentRoute: typeof AppObrasObraIdRdoRoute
    }
    '/app/obras/$obraId/compras/$compraId': {
      id: '/app/obras/$obraId/compras/$compraId'
      path: '/$compraId'
      fullPath: '/app/obras/$obraId/compras/$compraId'
      preLoaderRoute: typeof AppObrasObraIdComprasCompraIdRouteImport
      parentRoute: typeof AppObrasObraIdComprasRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFaturasRoute: typeof AdminFaturasRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFaturasRoute: AdminFaturasRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppObrasObraIdComprasRouteChildren {
  AppObrasObraIdComprasCompraIdRoute: typeof AppObrasObraIdComprasCompraIdRoute
}

const AppObrasObraIdComprasRouteChildren: AppObrasObraIdComprasRouteChildren = {
  AppObrasObraIdComprasCompraIdRoute: AppObrasObraIdComprasCompraIdRoute,
}

const AppObrasObraIdComprasRouteWithChildren =
  AppObrasObraIdComprasRoute._addFileChildren(
    AppObrasObraIdComprasRouteChildren,
  )

interface AppObrasObraIdRdoRouteChildren {
  AppObrasObraIdRdoRdoIdRoute: typeof AppObrasObraIdRdoRdoIdRoute
}

const AppObrasObraIdRdoRouteChildren: AppObrasObraIdRdoRouteChildren = {
  AppObrasObraIdRdoRdoIdRoute: AppObrasObraIdRdoRdoIdRoute,
}

const AppObrasObraIdRdoRouteWithChildren =
  AppObrasObraIdRdoRoute._addFileChildren(AppObrasObraIdRdoRouteChildren)

interface AppObrasRouteChildren {
  AppObrasObraIdComprasRoute: typeof AppObrasObraIdComprasRouteWithChildren
  AppObrasObraIdOrcamentoRoute: typeof AppObrasObraIdOrcamentoRoute
  AppObrasObraIdRdoRoute: typeof AppObrasObraIdRdoRouteWithChildren
}

const AppObrasRouteChildren: AppObrasRouteChildren = {
  AppObrasObraIdComprasRoute: AppObrasObraIdComprasRouteWithChildren,
  AppObrasObraIdOrcamentoRoute: AppObrasObraIdOrcamentoRoute,
  AppObrasObraIdRdoRoute: AppObrasObraIdRdoRouteWithChildren,
}

const AppObrasRouteWithChildren = AppObrasRoute._addFileChildren(
  AppObrasRouteChildren,
)

interface AppRouteChildren {
  AppCartoesRoute: typeof AppCartoesRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppConciliacaoRoute: typeof AppConciliacaoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContasBancariasRoute: typeof AppContasBancariasRoute
  AppContasPagarRoute: typeof AppContasPagarRoute
  AppContasReceberRoute: typeof AppContasReceberRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppObrasRoute: typeof AppObrasRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTransferenciasRoute: typeof AppTransferenciasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEstoqueAlmoxarifadosRoute: typeof AppEstoqueAlmoxarifadosRoute
  AppEstoqueMovimentacoesRoute: typeof AppEstoqueMovimentacoesRoute
  AppEstoqueProdutosRoute: typeof AppEstoqueProdutosRoute
  AppEstoqueRequisicoesRoute: typeof AppEstoqueRequisicoesRoute
  AppEstoqueSaldosRoute: typeof AppEstoqueSaldosRoute
  AppRhColaboradoresRoute: typeof AppRhColaboradoresRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartoesRoute: AppCartoesRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppConciliacaoRoute: AppConciliacaoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContasBancariasRoute: AppContasBancariasRoute,
  AppContasPagarRoute: AppContasPagarRoute,
  AppContasReceberRoute: AppContasReceberRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppObrasRoute: AppObrasRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTransferenciasRoute: AppTransferenciasRoute,
  AppIndexRoute: AppIndexRoute,
  AppEstoqueAlmoxarifadosRoute: AppEstoqueAlmoxarifadosRoute,
  AppEstoqueMovimentacoesRoute: AppEstoqueMovimentacoesRoute,
  AppEstoqueProdutosRoute: AppEstoqueProdutosRoute,
  AppEstoqueRequisicoesRoute: AppEstoqueRequisicoesRoute,
  AppEstoqueSaldosRoute: AppEstoqueSaldosRoute,
  AppRhColaboradoresRoute: AppRhColaboradoresRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
