/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppObrasRouteImport } from './routes/app.obras'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminFaturasRouteImport } from './routes/admin.faturas'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AppObrasObraIdRdoRouteImport } from './routes/app.obras.$obraId.rdo'
import { Route as AppObrasObraIdOrcamentoRouteImport } from './routes/app.obras.$obraId.orcamento'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturasRoute = AdminFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AppObrasObraIdRdoRoute = AppObrasObraIdRdoRouteImport.update({
  id: '/$obraId/rdo',
  path: '/$obraId/rdo',
  getParentRoute: () => AppObrasRoute,
} as any)
const AppObrasObraIdOrcamentoRoute = AppObrasObraIdOrcamentoRouteImport.update({
  id: '/$obraId/orcamento',
  path: '/$obraId/orcamento',
  getParentRoute: () => AppObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturas': typeof AdminFaturasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/obras/$obraId/orcamento': typeof AppObrasObraIdOrcamentoRoute
  '/app/obras/$obraId/rdo': typeof AppObrasObraIdRdoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturas': typeof AdminFaturasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/obras/$obraId/orcamento': typeof AppObrasObraIdOrcamentoRoute
  '/app/obras/$obraId/rdo': typeof AppObrasObraIdRdoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/faturas': typeof AdminFaturasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/obras/$obraId/orcamento': typeof AppObrasObraIdOrcamentoRoute
  '/app/obras/$obraId/rdo': typeof AppObrasObraIdRdoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturas'
    | '/admin/planos'
    | '/admin/tickets'
    | '/app/empresas'
    | '/app/obras'
    | '/admin/'
    | '/app/'
    | '/app/obras/$obraId/orcamento'
    | '/app/obras/$obraId/rdo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturas'
    | '/admin/planos'
    | '/admin/tickets'
    | '/app/empresas'
    | '/app/obras'
    | '/admin'
    | '/app'
    | '/app/obras/$obraId/orcamento'
    | '/app/obras/$obraId/rdo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/faturas'
    | '/admin/planos'
    | '/admin/tickets'
    | '/app/empresas'
    | '/app/obras'
    | '/admin/'
    | '/app/'
    | '/app/obras/$obraId/orcamento'
    | '/app/obras/$obraId/rdo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/obras': {
      id: '/app/obras'
      path: '/obras'
      fullPath: '/app/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturas': {
      id: '/admin/faturas'
      path: '/faturas'
      fullPath: '/admin/faturas'
      preLoaderRoute: typeof AdminFaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/obras/$obraId/rdo': {
      id: '/app/obras/$obraId/rdo'
      path: '/$obraId/rdo'
      fullPath: '/app/obras/$obraId/rdo'
      preLoaderRoute: typeof AppObrasObraIdRdoRouteImport
      parentRoute: typeof AppObrasRoute
    }
    '/app/obras/$obraId/orcamento': {
      id: '/app/obras/$obraId/orcamento'
      path: '/$obraId/orcamento'
      fullPath: '/app/obras/$obraId/orcamento'
      preLoaderRoute: typeof AppObrasObraIdOrcamentoRouteImport
      parentRoute: typeof AppObrasRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFaturasRoute: typeof AdminFaturasRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFaturasRoute: AdminFaturasRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppObrasRouteChildren {
  AppObrasObraIdOrcamentoRoute: typeof AppObrasObraIdOrcamentoRoute
  AppObrasObraIdRdoRoute: typeof AppObrasObraIdRdoRoute
}

const AppObrasRouteChildren: AppObrasRouteChildren = {
  AppObrasObraIdOrcamentoRoute: AppObrasObraIdOrcamentoRoute,
  AppObrasObraIdRdoRoute: AppObrasObraIdRdoRoute,
}

const AppObrasRouteWithChildren = AppObrasRoute._addFileChildren(
  AppObrasRouteChildren,
)

interface AppRouteChildren {
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppObrasRoute: typeof AppObrasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmpresasRoute: AppEmpresasRoute,
  AppObrasRoute: AppObrasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
